jobs:
  execute-reliably-plan:
    environment: acme
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: '#acme'
      uses: reliablyhq/actions/plan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: eddc7325-b081-4546-aa7a-716dc96a3716
        plan-id: 98b24def-7878-400d-b6f7-7b7f6295a5c0
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/reliablyhq/acme/tree/main/plans/98b24def-7878-400d-b6f7-7b7f6295a5c0"}]'
        reliably-host: app.reliably.dev
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/98b24def-7878-400d-b6f7-7b7f6295a5c0
name: Reliably Plan 98b24def-7878-400d-b6f7-7b7f6295a5c0
on:
  workflow_dispatch: null
