name: Execute a Reliably Plan

on:
  workflow_dispatch:

jobs:
  execute-reliably-plan:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: "#acme"
