jobs:
  execute-reliably-plan:
    environment: preprod
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: '#acme'
      uses: reliablyhq/actions/plan@main
      with:
        experiment-url: 
          https://app.reliably.com/api/v1/organization/423320d0-f114-44d8-ba48-788577b2c4ac/experiments/1f9ee18a-9b03-4e44-b197-def008ec914e/raw
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 423320d0-f114-44d8-ba48-788577b2c4ac
        plan-id: 55e8c598-fa50-46d6-aec7-7b8544afc971
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/reliablyhq/acme/tree/main/plans/55e8c598-fa50-46d6-aec7-7b8544afc971"}]'
        reliably-host: app.reliably.com
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/55e8c598-fa50-46d6-aec7-7b8544afc971
name: Reliably Plan 55e8c598-fa50-46d6-aec7-7b8544afc971
on:
  workflow_dispatch: null
