jobs:
  execute-reliably-plan:
    environment: preprod
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
      with:
        experiment-url: 
          https://app.reliably.com/api/v1/organization/423320d0-f114-44d8-ba48-788577b2c4ac/experiments/1f9ee18a-9b03-4e44-b197-def008ec914e/raw
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 423320d0-f114-44d8-ba48-788577b2c4ac
        plan-id: 7c1cc4a3-741c-4658-b0a2-788ae1b79627
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/reliablyhq/acme/tree/main/plans/7c1cc4a3-741c-4658-b0a2-788ae1b79627"}]'
        reliably-host: app.reliably.com
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/7c1cc4a3-741c-4658-b0a2-788ae1b79627
name: Reliably Plan 7c1cc4a3-741c-4658-b0a2-788ae1b79627
on:
  workflow_dispatch: null
